// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzFKQK4LN90btO6aWpexAl3Ds2KsE1MPU',
    appId: '1:565947918706:web:7dca90e72b45ceee4255eb',
    messagingSenderId: '565947918706',
    projectId: 'coffee-shop-bbe30',
    authDomain: 'coffee-shop-bbe30.firebaseapp.com',
    storageBucket: 'coffee-shop-bbe30.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfEP51u9qRPeop05lVOiXpGnK2G40hcQU',
    appId: '1:565947918706:android:e7f3ca29ab1c45514255eb',
    messagingSenderId: '565947918706',
    projectId: 'coffee-shop-bbe30',
    storageBucket: 'coffee-shop-bbe30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOPeD7L8ESoFOVwsk-2wQHi6lcGhSvqDM',
    appId: '1:565947918706:ios:e2bc475a2bc2bdc94255eb',
    messagingSenderId: '565947918706',
    projectId: 'coffee-shop-bbe30',
    storageBucket: 'coffee-shop-bbe30.appspot.com',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOPeD7L8ESoFOVwsk-2wQHi6lcGhSvqDM',
    appId: '1:565947918706:ios:e2bc475a2bc2bdc94255eb',
    messagingSenderId: '565947918706',
    projectId: 'coffee-shop-bbe30',
    storageBucket: 'coffee-shop-bbe30.appspot.com',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzFKQK4LN90btO6aWpexAl3Ds2KsE1MPU',
    appId: '1:565947918706:web:1a50be07fed47d4a4255eb',
    messagingSenderId: '565947918706',
    projectId: 'coffee-shop-bbe30',
    authDomain: 'coffee-shop-bbe30.firebaseapp.com',
    storageBucket: 'coffee-shop-bbe30.appspot.com',
  );
}
